export const GET_STORY_LIST_LOADING = 'GET_STORY_LIST_LOADING';
export const GET_STORY_LIST_SUCCESS = 'GET_STORY_LIST_SUCCESS';
export const GET_STORY_LIST_ERROR = 'GET_STORY_LIST_ERROR';
export const RESTORE_STORY_LIST = 'RESTORE_STORY_LIST';
